name: Build and Release

on:
  push:
    tags:
      - 'v*' # Triggers on version tags like v1.0, v1.1.0, etc.

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Build Release APK
        run: ./gradlew assembleRelease

      - name: Build Release AAB
        run: ./gradlew bundleRelease

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          name: "DaysLeft ${{ github.ref_name }}"
          body: |
            # DaysLeft ${{ github.ref_name }}
            
            New release of the DaysLeft Android app for tracking important events and days remaining.
            
            **Downloads:**
            - 📱 **APK**: For direct installation on Android devices
            - 📦 **AAB**: For Google Play Store distribution
            
            **Installation:**
            1. Download the APK file
            2. Enable "Install from unknown sources" in your Android settings
            3. Install the APK file
            
            ---
            Built automatically from commit: ${{ github.sha }}
          files: |
            app/build/outputs/apk/release/*.apk
            app/build/outputs/bundle/release/*.aab
